### ISSUE TITLE
Style sign up/application page

### ISSUE THREAD

**Issue by zackharley** [qhacks/hacker-dashboard#17]
**Problem**
We need to determine sign up logic!

**Requirements**
- [ ] A signup screen
    - [ ] Can enter an email address and click apply
    - [ ] After button click, redirect to application form with email prefilled
- [ ] Application screen
    - [ ] Having a separate application screen will allow us to prefill people's email addresses from a URL param, i.e. `/application?email=zack@qhacks.io`

**Comment by RobertWSaunders** [comment]
@zackharley my thoughts we that `signup` and `apply` were the same for our app. Regardless of the routes and params passed in there should only be one of them.

**Comment by zackharley** [comment]
I think `login` and `signup` should be similar, and that `apply` would be its own full screen form

**Comment by RobertWSaunders** [comment]
I'm confused, what is the point of the signup page your proposal? purely just a email field? I don't see the value in this, signing up is the same as applying, so just making one full screen form works.
