### ISSUE TITLE
Send email upon successful application

### ISSUE THREAD

**Issue by zackharley** [qhacks/hacker-dashboard#18]
**Problem**
We should notify the user by email that they have successfully applied to QHacks 2018.

**Requirements**
- [ ] Create a dynamic HTML email template
- [ ] That email can be triggered via a third-party API

**Comment by RobertWSaunders** [comment]
Will add this in the reset PR, mailing is setup, this should be easy, going to have to HTML templating improved however. Need to come up with a standard, maybe @AviIhej or @ccrowley96 can look into templates

**Comment by zackharley** [comment]
https://mjml.io/

**Comment by RobertWSaunders** [comment]
Implemented! Need to add email templates but base feature is done, another issue for templates is open #37

**Comment by RobertWSaunders** [comment]
Implemented! Need to add email templates but base feature is done, another issue for templates is open #37
