### ISSUE TITLE
Create post-application/post-login splash screen

### ISSUE THREAD

**Issue by zackharley** [qhacks/hacker-dashboard#19]
**Problem**
The user needs to be redirected to a screen after successfully applying or logging in. Will this be a temporary splash screen? Can we build the first iteration of the dashboard in time for us to show the users info?

**Requirements**
*TBD*

**Comment by RobertWSaunders** [comment]
@zackharley I was thinking the `/dashboard` route can still be used for the splash screen, but if we can't build something out in time it'll just have some info. I think I can take care of a user profile screen, but that would be separate from the dashboard screen. For now, if we aim to have a nav bar at the top with the crown in the top left, followed by a Dashboard link, and then a profile link the top right that would be great. All the dashboard would have to say is thank you for applying and that more info will be posted here soon, what are your thoughts? Lets talk tonight

**Comment by zackharley** [comment]
Works with me!
