### ISSUE TITLE
Add custom winston logger on backend, including transports

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/hacker-dashboard#24]
**Problem**

Create a custom logger that includes transports for persisting logs, also make custom levels, add colors!

**Requirements**
- [ ] Add transports for log persistence

**Comment by zackharley** [comment]
Good call! I think we can upgrade the priority for this. I also think that this is an MVP feature we need.

**Comment by RobertWSaunders** [comment]
We have one! Could be improved but can close this for now. 👍
